AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world api.
Resources:
  HelloAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: 2.0
        info:
          title:
            Ref: AWS::StackName
        paths:
          "/hello":
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FnHelloAPI.Arn}/invocations
                responses: {}
        swagger: '2.0'
  FnHelloAPI:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./src
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /hello
            Method: ANY
            RestApiId: !Ref HelloAPI
  FnHelloAPIPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt FnHelloAPI.Arn
      Action: lambda:InvokeFunction
      Principal: "apigateway.amazonaws.com"
Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref HelloAPI
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/Prod'
